name:                mutter
version:             0.1.0.0
github:              "hue-plu/mutter"
license:             MIT
author:              "hue-plu"
maintainer:          "shuetwitter@gmail.com"
copyright:           "2021 hue-plu"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/hue-plu/mutter#readme>

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - GADTs
  - Arrows
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications
  - StandaloneDeriving
  - TypeSynonymInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - DuplicateRecordFields
  - RankNTypes
  - LambdaCase
  - NamedFieldPuns

dependencies:
- base
- bytestring
- mtl
- extra
- morpheus-graphql
- morpheus-graphql-core
- regex-tdfa        >=1.3.1.0
- scotty
- text
- opaleye
- product-profunctors
- postgresql-simple
- postgresql-simple-url
- time
- transformers
- transformers-base
- monad-control


library:
  source-dirs: src

executables:
  mutter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mutter
  study-exe:
    main:                Main.hs
    source-dirs:         study
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []

tests:
  mutter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mutter
