# resolver:
#   url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/17/12.yaml

resolver: nightly-2021-05-20

packages:
- .

extra-deps:
  - postgresql-simple-url-0.2.1.0
