type Murmur {
  id: Int!
  text: String!
  user: User!
}

type User {
  id: Int!
  name: String!
  murmurs: [Murmur!]!
}

type Query {
  user(name: String! = ".*"): User
  murmur(text: String! = ".*"): Murmur
  users: [User!]!
  murmurs: [Murmur!]!
}
